name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  ros:
    runs-on: ubuntu-22.04
    steps:
    - name: Install wget
      run: sudo apt-get install -y wget

    - name: Download MuJoCo
      run: |
        wget https://mujoco.org/download/mujoco210-linux-x86_64.tar.gz -O /tmp/mujoco.tar.gz
        mkdir -p /root/mujoco-3.1.6
        tar -xzf /tmp/mujoco.tar.gz -C /root/mujoco-3.1.6 --strip-components=1

    - uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: humble
    - uses: ros-tooling/action-ros-ci@v0.3
      with:
        target-ros2-distro: humble
